---
title: "R Notebook"
output: html_notebook
---

IMPACT REPORT DATA SETUP


```{r Librarries, message=FALSE, warning=FALSE, paged.print=FALSE}
library(readxl)
library(tidyverse)
library(stringr)

```


```{r RTV Graduated Clusters, message=FALSE, warning=FALSE}

# Load the dataset
df_raw <- read_excel("G:/Shared drives/PEAL Master/03.PEAL Analytics Unit Folder/Impact Report Dashboard/RTV Graduated Clusters.xlsx", 
                     sheet = "RTV Graduated Clusters", col_names = FALSE)


# Set the first row as column names
colnames(df_raw) <- as.character(df_raw[1, ])
df_raw <- df_raw[-1, ]  # Remove the row that became column names

# Extract the Income Streams row. To be used as the Period column
income_streams <- df_raw[1, ]  # 2nd row is Income Streams
df_data <- df_raw[-1, ]        # Remove Income Streams row from data

periods <- unlist(income_streams)[-1]  # exclude the first column

df_long <- df_data %>%
  pivot_longer(cols = -1, names_to = "Cohort_District", values_to = "Amount") %>%
  mutate(Year = rep(periods, each = nrow(df_data))) %>%  # 'Year' from income_streams
  rename(`Income Stream` = 1)  # First column is the income stream category

# Extract cohort year and clean district names

Graduated_clusters_RTV <- df_long %>%
  mutate(
    Cohort = str_extract(Cohort_District, "\\b20\\d{2}\\b"),
    District = Cohort_District %>%
      str_remove_all("\\d+") %>%           # Remove digits
      str_remove_all("Cohort") %>%         # Remove the word 'Cohort'
      str_replace_all("-", "") %>%         # Remove hyphens
      str_remove("RTV") %>%                # Remove 'RTV' if still present
      str_squish()                         # Trim and clean up whitespace
  ) %>%
  select(District, `Income Stream`, Cohort, Year, Amount)

Graduated_clusters_RTV <- Graduated_clusters_RTV %>%
  mutate(Status = "RTV")


```

CONTROL DATASET

```{r Control Graduated Clusters, message=FALSE, warning=FALSE, paged.print=FALSE}

# Load the dataset
df_raw_control <- read_excel("G:/Shared drives/PEAL Master/03.PEAL Analytics Unit Folder/Impact Report Dashboard/Control Graduated Clusters.xlsx", 
                     sheet = "Control", col_names = FALSE)


# Set the first row as column names
colnames(df_raw_control) <- as.character(df_raw_control[1, ])
df_raw_control_v1 <- df_raw_control[-1, ]  # Remove the row that became column names

# Extract the Income Streams row. To be used as the Period column
income_streams <- df_raw_control_v1[1, ]  # 2nd row is Income Streams
df_raw_control_v2 <- df_raw_control_v1[-1, ]        # Remove Income Streams row from data

periods <- unlist(income_streams)[-1]  # exclude the first column

df_raw_control_v3 <- df_raw_control_v2 %>%
  pivot_longer(cols = -1, names_to = "Cohort_District", values_to = "Amount") %>%
  mutate(Year = rep(periods, each = nrow(df_raw_control_v2))) %>%  # 'Year' from income_streams
  rename(`Income Stream` = 1)  # First column is the income stream category

# Extract cohort year and clean district names

Graduated_clusters_control <- df_raw_control_v3 %>%
  mutate(
    Cohort = str_extract(Cohort_District, "\\b20\\d{2}\\b"),
    District = Cohort_District %>%
      str_remove_all("\\d+") %>%           # Remove digits
      str_remove_all("Cohort") %>%         # Remove the word 'Cohort'
      str_replace_all("-", "") %>%         # Remove hyphens
      str_remove("RTV") %>%                # Remove 'RTV' if still present
      str_squish()                         # Trim and clean up whitespace
  ) %>%
  select(District, `Income Stream`, Cohort, Year, Amount)

Graduated_clusters_control <- Graduated_clusters_control %>%
  mutate(Status = "Control")

```

GRADUATED_CLUSTERS_CONTROL_RTV

```{r Graduated Clusters Control and RTV, message=FALSE, warning=FALSE, paged.print=FALSE}
combined_RTV_Control <- bind_rows(Graduated_clusters_RTV, Graduated_clusters_control)  %>% view()

```


RTV OVERALL


```{r RTV Overall, message=FALSE, warning=FALSE, paged.print=FALSE}

# Load the dataset
raw_rtv_overall <- read_excel("G:/Shared drives/PEAL Master/03.PEAL Analytics Unit Folder/Impact Report Dashboard/RTV Overall.xlsx", 
                     sheet = "overall", col_names = FALSE)

# Set first row as column names
colnames(raw_rtv_overall) <- as.character(raw_rtv_overall[1, ])

# Remove the first row (it’s now column headers)
raw_rtv_overall <- raw_rtv_overall[-1, ]

# Check column names to confirm
# colnames(raw_rtv_overall)

# Remove columns with missing or blank names
raw_rtv_overall_v1 <- raw_rtv_overall[, colnames(raw_rtv_overall) != "" & !is.na(colnames(raw_rtv_overall))]

# Replace #DIV/0! with NA and convert numeric columns
raw_rtv_overall_v2 <- raw_rtv_overall_v1 %>%
  mutate(across(
    .cols = -`Income Streams`,  # exclude the text column
    .fns = ~ na_if(., "#DIV/0!") %>% as.numeric()
  ))


# Convert to long format
raw_rtv_overall_v3 <- raw_rtv_overall_v2 %>%
  pivot_longer(
    cols = -`Income Streams`,     # All columns except "Income Streams"
    names_to = "Period",          # Name for new "period" column
    values_to = "Amount"           # Name for new value column
  )

RTV_Overall <- raw_rtv_overall_v3 %>%
  mutate(Status = "RTV")

view(RTV_Overall)
```


CONTROL OVERALL

```{r Control Overall, message=FALSE, warning=FALSE, paged.print=FALSE}

# Load the dataset
df_raw_Control_overall <- read_excel("G:/Shared drives/PEAL Master/03.PEAL Analytics Unit Folder/Impact Report Dashboard/Control Overall_Table 15.xlsx", 
                     sheet = "Overall", col_names = FALSE)


# Set first row as column names
colnames(df_raw_Control_overall) <- as.character(df_raw_Control_overall[1, ])

# Remove the first row (it’s now column headers)
df_raw_Control_overall <- df_raw_Control_overall[-1, ]

# Check column names to confirm
# colnames(df_raw_Control_overall)

# Remove columns with missing or blank names
df_raw_Control_overall_v1 <- df_raw_Control_overall[, colnames(df_raw_Control_overall) != "" & !is.na(colnames(df_raw_Control_overall))]

# Replace #DIV/0! with NA and convert numeric columns
df_raw_Control_overall_v2 <- df_raw_Control_overall_v1 %>%
  mutate(across(
    .cols = -`Income Streams`,  # exclude the text column
    .fns = ~ na_if(., "#DIV/0!") %>% as.numeric()
  ))


# Convert to long format
df_raw_Control_overall_v3 <- df_raw_Control_overall_v2 %>%
  pivot_longer(
    cols = -`Income Streams`,     # All columns except "Income Streams"
    names_to = "Period",          # Name for new "period" column
    values_to = "Amount"           # Name for new value column
  )

Control_Overall <- df_raw_Control_overall_v3 %>%
  mutate(Status = "Control")

view(Control_Overall)

```


COMBINED_CONTROL_RTV_OVERALL

```{r}
Overall_RTV_Control_Overall <- bind_rows(RTV_Overall, Control_Overall)  %>% view()

```


GRADUATED COHORTS

RTV GRADUATED COHORTS

```{r RTV Graduated Cohorts, message=FALSE, warning=FALSE, paged.print=FALSE}

# Load the dataset
raw_rtv_graduated_cohorts <- read_excel("G:/Shared drives/PEAL Master/03.PEAL Analytics Unit Folder/Impact Report Dashboard/Table_16_RTV_Graduated_Cohorts.xlsx", 
                     sheet = "RTV Graduated Cohorts", col_names = FALSE)

# Set first row as column names
colnames(raw_rtv_graduated_cohorts) <- as.character(raw_rtv_graduated_cohorts[1, ])

# Remove the first row (it’s now column headers)
raw_rtv_graduated_cohorts <- raw_rtv_graduated_cohorts[-1, ]

# Check column names to confirm
# colnames(raw_rtv_graduated_cohorts)

# Remove columns with missing or blank names
raw_rtv_graduated_cohorts_v1 <- raw_rtv_graduated_cohorts[, colnames(raw_rtv_graduated_cohorts) != "" & !is.na(colnames(raw_rtv_graduated_cohorts))]

# Replace #DIV/0! with NA and convert numeric columns
raw_rtv_graduated_cohorts_v2 <- raw_rtv_graduated_cohorts_v1 %>%
  mutate(across(
    .cols = -`Income Streams`,  # exclude the text column
    .fns = ~ na_if(., "#DIV/0!") %>% as.numeric()
  ))


# Convert to long format
raw_rtv_graduated_cohorts_v3 <- raw_rtv_graduated_cohorts_v2 %>%
  pivot_longer(
    cols = -`Income Streams`,     # All columns except "Income Streams"
    names_to = "Period",          # Name for new "period" column
    values_to = "Amount"           # Name for new value column
  )

RTV_Graduated_Cohorts <- raw_rtv_graduated_cohorts_v3 %>%
  mutate(Status = "RTV")

view(RTV_Graduated_Cohorts)

```


CONTROL GRADUATED COHORTS

```{r Control Graduated Cohorts, message=FALSE, warning=FALSE, paged.print=FALSE}

# Load the dataset
raw_control_graduated_cohorts <- read_excel("G:/Shared drives/PEAL Master/03.PEAL Analytics Unit Folder/Impact Report Dashboard/Table_16_Control_Graduated_Cohorts.xlsx", 
                     sheet = "Control Graduated Cohorts", col_names = FALSE)

# Set first row as column names
colnames(raw_control_graduated_cohorts) <- as.character(raw_control_graduated_cohorts[1, ])

# Remove the first row (it’s now column headers)
raw_control_graduated_cohorts <- raw_control_graduated_cohorts[-1, ]

# Check column names to confirm
# colnames(raw_rtv_graduated_cohorts)

# Remove columns with missing or blank names
raw_control_graduated_cohorts_v1 <- raw_control_graduated_cohorts[, colnames(raw_control_graduated_cohorts) != "" & !is.na(colnames(raw_control_graduated_cohorts))]

# Replace #DIV/0! with NA and convert numeric columns
raw_control_graduated_cohorts_v2 <- raw_control_graduated_cohorts_v1 %>%
  mutate(across(
    .cols = -`Income Streams`,  # exclude the text column
    .fns = ~ na_if(., "#DIV/0!") %>% as.numeric()
  ))


# Convert to long format
raw_control_graduated_cohorts_v3 <- raw_control_graduated_cohorts_v2 %>%
  pivot_longer(
    cols = -`Income Streams`,     # All columns except "Income Streams"
    names_to = "Period",          # Name for new "period" column
    values_to = "Amount"           # Name for new value column
  )

Control_Graduated_Cohorts <- raw_control_graduated_cohorts_v3 %>%
  mutate(Status = "Control")

view(Control_Graduated_Cohorts)

```


COMBINED_CONTROL__RTV_GRADUATED_COHORTS

```{r}

combined_RTV_Control_Graduated <- bind_rows(RTV_Graduated_Cohorts, Control_Graduated_Cohorts)  %>% view()

```


WEIGHTS

```{r}

# Load the dataset
raw_weights <- read_excel("G:/Shared drives/PEAL Master/03.PEAL Analytics Unit Folder/Impact Report Dashboard/Weights.xlsx", 
                     sheet = "Weights", col_names = TRUE)

raw_weights_v1 <- raw_weights %>%
  mutate(
    Year = str_extract(Cohort, "\\b\\d{4}\\b"),
    
    District = Cohort %>%
      str_remove_all("(?i)Cohort") %>%
      str_remove_all("(?i)Peer") %>%
      str_remove_all("\\b\\d{4}\\b") %>%
      str_squish(),

    Status = case_when(
      str_detect(Cohort, "(?i)Peer") ~ "Peer",  # if "Peer" is found (case-insensitive)
      TRUE ~ "RTV"                             # otherwise
    )
  )

raw_weights_v2 <- raw_weights_v1 %>%
  select(-Cohort) %>%           # Drop original Cohort column
  rename(Cohort = Year)        # Rename Year to Cohort

# 2nd Pivot

raw_weights_v3 <- raw_weights_v2 %>%
  pivot_longer(
    cols = -c(`Region`, `HHs`, `Cohort`, `District`, `Status`),     # All columns except "Income Streams"
    names_to = "Year",          # Name for new "period" column
    values_to = "Weight"           # Name for new value column
  )

#Remove the word 'Weight-'

raw_weights_v4 <- raw_weights_v3 %>%
  mutate(Year = str_remove(Year, "^Weight-"))

view(raw_weights_v4)

```

TOPLINE ALL COHORTS

RTV

```{r}

# Load the dataset
Topline_All_Cohorts_RTV <- read_excel("G:/Shared drives/PEAL Master/03.PEAL Analytics Unit Folder/Impact Report Dashboard/Topline_All_Cohorts_RTV.xlsx", 
                     sheet = "Topline", col_names = TRUE)


Topline_All_Cohorts_RTV_v1 <- Topline_All_Cohorts_RTV %>%
  pivot_longer(
    cols = -c(`Topline`),     # All columns except "Income Streams"
    names_to = "Year",          # Name for new "period" column
    values_to = "Amount"           # Name for new value column
  ) %>% view()
  
```

CONTROL

```{r}

# Load the dataset
Topline_All_Cohorts_Control <- read_excel("G:/Shared drives/PEAL Master/03.PEAL Analytics Unit Folder/Impact Report Dashboard/Topline_All_Cohorts_Control.xlsx", 
                     sheet = "Control", col_names = TRUE)


Topline_All_Cohorts_Control_v1 <- Topline_All_Cohorts_Control %>%
  pivot_longer(
    cols = -c(`Topline`),     # All columns except "Income Streams"
    names_to = "Year",          # Name for new "period" column
    values_to = "Amount"           # Name for new value column
  ) %>% view()
```

